services:
  - type: web
    name: event-ticketing-backend
    env: go
    buildCommand: go build -o server main.go
    startCommand: ./server
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://<TÀI_KHOẢN>:<MẬT_KHẨU>@<HOST>/<DB>?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: REDIS_URL
        value: redis://default:<password>@<host>:<port>
