basePath: /
definitions:
  controllers.OrderDetail:
    properties:
      event_date:
        type: string
      event_name:
        type: string
      order_id:
        type: string
      purchase_time:
        type: string
      quantity:
        type: integer
      status:
        type: string
      ticket_price:
        type: number
      total_price:
        type: number
    type: object
  models.Event:
    properties:
      available_tickets:
        description: so ve con lai
        type: integer
      created_at:
        description: thoi gian su kien
        type: string
      date:
        description: ngay gio
        type: string
      description:
        type: string
      id:
        type: string
      image_url:
        description: anh su kien
        type: string
      location:
        type: string
      name:
        description: thong tin
        type: string
      ticket_price:
        type: number
      total_tickets:
        description: tong ve ban
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: string
      is_verified:
        description: đã xác minh Gmail chưa
        type: boolean
      name:
        type: string
      role:
        description: '"user" hoặc "admin"'
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: your_email@example.com
    name: Dự án nhóm - sử dụng với ChatGPT
  description: API backend quản lý sự kiện và đặt vé bằng Golang
  title: Event Ticketing API
  version: "1.0"
paths:
  /api/events:
    get:
      description: Trả về tất cả sự kiện trong hệ thống
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lấy danh sách sự kiện
      tags:
      - Event
    post:
      consumes:
      - application/json
      description: Admin tạo một sự kiện mới
      parameters:
      - description: Thông tin sự kiện
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Tạo sự kiện mới
      tags:
      - Event
  /api/events/{id}:
    delete:
      description: Admin xoá một sự kiện
      parameters:
      - description: ID sự kiện
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Xoá sự kiện
      tags:
      - Event
    get:
      description: Lấy thông tin sự kiện theo ID
      parameters:
      - description: ID sự kiện
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lấy chi tiết sự kiện
      tags:
      - Event
    put:
      consumes:
      - application/json
      description: Admin cập nhật thông tin một sự kiện
      parameters:
      - description: ID sự kiện
        in: path
        name: id
        required: true
        type: string
      - description: Thông tin cập nhật
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Cập nhật sự kiện
      tags:
      - Event
  /api/login:
    post:
      consumes:
      - application/json
      description: Đăng nhập và trả về JWT token
      parameters:
      - description: Thông tin đăng nhập
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Đăng nhập
      tags:
      - Auth
  /api/orders/my:
    get:
      description: Lấy danh sách các đơn hàng đã đặt của người dùng hiện tại
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.OrderDetail'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Xem đơn hàng của tôi
      tags:
      - Order
  /api/register:
    post:
      consumes:
      - application/json
      description: Đăng ký tài khoản mới và gửi mã xác nhận qua email
      parameters:
      - description: Thông tin người dùng
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Đăng ký tài khoản
      tags:
      - Auth
  /api/verify-email:
    post:
      consumes:
      - application/json
      description: Gửi mã xác nhận để xác thực tài khoản email
      parameters:
      - description: Email và mã xác nhận
        in: body
        name: input
        required: true
        schema:
          properties:
            code:
              type: string
            email:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Xác minh email
      tags:
      - Auth
swagger: "2.0"
